spring.application.name=ProjetoFinanceiro
# ===============================
# DATASOURCE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:8080/MoneyMind
spring.datasource.username=postgres
spring.datasource.password=manager101

# ===============================
# JPA
# ===============================

# ===============================
# SQL INIT
# ===============================
server.port=8081